---
default:
  image: alpine:latest
  tags:
    - docker
  interruptible: true
  before_script:
    - if [[ ! -d $CI_PROJECT_DIR/.pkg_cache ]] ; then mkdir "$CI_PROJECT_DIR/.pkg_cache" ; fi
    - ln -s "$CI_PROJECT_DIR/.pkg_cache" /etc/apk/cache
    - apk update

stages:
  - code-analysis
  - build
  - runtime-tests
  - release

cache:
  paths:
    - .pkg_cache/
    - .wine/

cppcheck:
  stage: code-analysis
  script:
    - apk add cppcheck
    - cppcheck src/main.c tests/test.c

compile:
  stage: build
  script:
    - apk add make mingw-w64-gcc
    - make
    - make tests
  artifacts:
    name: proton-shunt
    paths:
      - build/
    expire_in: 1h

shunt-test:
  stage: runtime-tests
  variables:
    DISPLAY: ":99"
    WINEPREFIX: "$CI_PROJECT_DIR/.wine"
  script:
    - apk add wine xvfb xvfb-run
    - echo "build/tests/test.exe" > proton-shunt.cfg
    - winecfg
    - chmod u+x pipeline/test.sh
    - ./pipeline/test.sh

release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - apk add bash findutils github-cli
    - mv build/proton-shunt.exe "build/proton-shunt-$CI_COMMIT_TAG.exe"
    - chmod u+x pipeline/github-release.sh
    - ./pipeline/github-release.sh
